### ISSUE TITLE
Support configuring multiple directories for a single agent

### ISSUE THREAD

**Issue by kevin-johnson-shopify** [parruda/claude-swarm#14]
### Description
Currently, agents can only be configured with a single directory. There's a need to allow agents to access multiple directories across different locations in the file system.

### Use Case
For specialized agents like `infrastructure_engineer`, it's common to have relevant code spread across multiple repositories and locations. For example:
- `/home/user/repos/company/infrastructure`
- `/home/user/workspace/platform/services/payment/infrastructure`
- Other infrastructure-related directories

Having to switch between directories or create multiple agents for the same purpose is inefficient.

### Proposed Solution
Update the directory configuration to accept either a string (current behavior) or an array of strings:

```yaml
# Current (still supported)
directory: "/path/to/single/directory"

# New capability
directory: 
  - "/path/to/first/directory"
  - "/path/to/second/directory"
  - "/path/to/third/directory"
```

### Additional Context
- Claude code already supports `--add-dir` functionality, suggesting this pattern is useful
- This would improve workflow efficiency for agents that need cross-repository awareness
- Maintains backward compatibility with existing single-directory configurations

### Expected Behavior
When multiple directories are configured, the agent should have access to all specified directories and be able to search, read, and operate across all of them seamlessly.
