### ISSUE TITLE
Feature request: composable `claude-swarm.yml`

### ISSUE THREAD

**Issue by stevegeek** [parruda/claude-swarm#17]
Related to https://github.com/parruda/claude-swarm/issues/11

It could be useful and make the `claude-swarm.yml` more easily maintained if one could compose various files, specifically im thinking about the prompts. Eg it would be nice if instead of specifying the prompt directly in the YML one could instead point to an set of external md files say, eg

```yaml
version: 1
swarm:
  name: "MyProj Swarm"
  main: lead_developer
  instances:
    lead_developer:
      description: "Lead developer who coordinates the team and makes architectural decisions"
      directory: .
      model: sonnet
      prompt_files: 
         - /shared/prompts/lead_developer.md
         - my_proj_lead_developer.md
```
